# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nome_do_botao = QtWidgets.QPushButton(self.centralwidget)
        self.nome_do_botao.setGeometry(QtCore.QRect(475, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nome_do_botao.setFont(font)
        self.nome_do_botao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nome_do_botao.setStyleSheet("QPushButton {\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"color: #FFFFFF;\n"
"\n"
"background-color: #3FB18D;\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-top: #DADADA;\n"
"border-right: #DADADA;\n"
"border-bottom: #DADADA;\n"
"border-left: #DADADA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"color: #FFFFFF;\n"
"\n"
"background-color: #3FB18D;\n"
"\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: #000000\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: #D3D3D3;\n"
"}\n"
"")
        self.nome_do_botao.setObjectName("nome_do_botao")
        self.nome_do_campo = QtWidgets.QLineEdit(self.centralwidget)
        self.nome_do_campo.setGeometry(QtCore.QRect(406, 250, 245, 27))
        self.nome_do_campo.setStyleSheet("QLineEdit {\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: #FFFFFF;\n"
"height: 25px;\n"
"border-radius: 5px;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: #6B6E6C\n"
"\n"
"}")
        self.nome_do_campo.setText("")
        self.nome_do_campo.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_do_campo.setReadOnly(False)
        self.nome_do_campo.setPlaceholderText("")
        self.nome_do_campo.setObjectName("nome_do_campo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nome_do_botao.setText(_translate("MainWindow", "OI"))
